### PR TITLE
Dynamic Port Selection

### PR DESCRIPTION
**Pull request by mdornseif**
I had serious issues with google-datastore-emulator not being able to be run in parallel tests.
The issue was port selection: At least in the default configuration the port was not selected dynamically. 

This PR solves that in considering the provided port number as PREFERRED port. If this port is not free, the next free port will be selected. So instantiation should never vail due to listen port not available.

### CODE REVIEW

**Comment by ert78gb** [comment]
Am I understand well, you would like to run integration test parallel and you would like to spin up a new emulator instance for every test. Don't you think it will very slow and resource hungry? In this case your test runner should guaranteed the isolated environments otherwise the environment settings will override eachother.

I support the dynamic port selection.

**Comment by mdornseif** [comment]
There will be resource issues with too many emulators, you are right. Tests on jest with default setup would have one datastore emulator per CPU core. Each emulator would use about 100M.

My main concern is, that I want to be able to run tests at the command line while I have also the tests running in the debugger. Currently for me tests are failing in all kinds of situations because of port allocation issues. Also, I do not get any decent failure message on port allocation issues but a timeout. I guess that is due to bad promise handling on my end, but this is hard to debug.

**Comment by ert78gb** [comment]
The locally installed SDK opens random port if the provided port in used. The docker case we have to provide the host port.
I like this PR. If you don't have time I can implement this feature tomorrow.

**Comment by mdornseif** [comment]
I think if you implement it, it would be better alligned with the rest of the library. So I would be thankful if you go ahead with it.

**Comment by ert78gb** [comment]
@mdornseif The feature landed in `5.2.0` if you are experiencing any issue feel free to report.
Thx for the port already in used "bug"

**Pull request closed without merging**
